image: cirrusci/flutter:stable

stages:
  - build
  
build:
  stage: build
  script:
    - cd  client
    - flutter build apk
    - ls
  artifacts:
    paths:
    - build/app/outputs/apk/release/app-release.apk
    expire_in: 1 year
  tags:
    - shared