image: cirrusci/flutter:stable

stages:
  - build
  
build:
  stage: build
  script:
    - cd  client
    - flutter build apk
    - ls
  artifacts:
    paths:
    - app/build/outputs/
  tags:
    - shared