image: cirrusci/flutter:stable

stages:
  - build
  
build:
  stage: build
  script:
    - cd  client
    - flutter build apk
    - ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
  artifacts:
    paths:
    - build/
    expire_in: 1 year
  tags:
    - shared